### ISSUE TITLE
Pass in list of pipelines to install

### ISSUE THREAD

**Issue by pwoods25443** [GlobalFishingWatch/pipe-airflow#3]
We need to specify the set of pipelines that should be installed (e.g. https://github.com/GlobalFishingWatch/deploy/blob/pipe-airflow/pipe-airflow/install_dags.sh)

The list of pipelines should be passed in to the container in an environment variable or in a file in a mounted folder so that is can be specified in the kubernetes yaml file (eg. https://github.com/GlobalFishingWatch/deploy/blob/pipe-airflow/pipe-airflow/dev.yaml )

**Comment by andres-arana** [comment]
Done on the latest master.
